steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'us-central1-docker.pkg.dev/saifuls-playground/python-app/python-work:sql',
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'us-central1-docker.pkg.dev/saifuls-playground/python-app/python-work:sql']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'python-mysql'
      - '--image'
      - 'us-central1-docker.pkg.dev/saifuls-playground/python-app/python-work:sql'
      - '--no-allow-unauthenticated'
      - '--vpc-connector'
      - 'serverless-vpc-connector'
      - '--set-cloudsql-instances'
      - 'private-instance-5606fd01'
      - '--log-http'
      - '--region'
      - 'us-central1'