# Further reading:
#   Cloud Run IAM permissions                 - https://cloud.google.com/run/docs/deploying
#   Artifact Registry IAM permissions         - https://cloud.google.com/artifact-registry/docs/access-control#roles
#   Container Registry vs Artifact Registry   - https://cloud.google.com/blog/products/application-development/understanding-artifact-registry-vs-container-registry
#   Principle of least privilege              - https://cloud.google.com/blog/products/identity-security/dont-get-pwned-practicing-the-principle-of-least-privilege

name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "master" ]

env:
  PROJECT_ID: "saifuls-playground"
  GAR_LOCATION: "us-central1"
  SERVICE: "python-work"
  REGION: "us-central1"

jobs:
  pylint:
    uses: ./.github/workflows/pylint.yml

  push_aws_ecr:
    needs: [ pylint ]
    uses: ./.github/workflows/docker-image.yml
    with:
      registry: 940443069190.dkr.ecr.ap-southeast-1.amazonaws.com
    secrets: inherit

  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    needs: [pylint, push_aws_ecr]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          access_token_lifetime: 300
          workload_identity_provider: 'projects/294059432651/locations/global/workloadIdentityPools/github-action-pool-f8f1b059/providers/github-action-provider-f8f1b059'
          service_account: 'github-action-sa@saifuls-playground.iam.gserviceaccount.com'

      # END - Docker auth and build
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          # NOTE: If using a pre-built image, update the image name here
          image: us-central1-docker.pkg.dev/saifuls-playground/python-app/python-work:${{ github.sha }}

      - name: 'Run shell commands'
        run: |
          gcloud run services update lsx-server --region='us-west1' --command='echo "Hello, world!"'    

      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}

